language: node_js
sudo: false
node_js:
  - 'stable'

notifications:
  email: false

cache:
  directories:
    - node_modules
    - jspm_packages

branches:
  only:
    - master
    - develop

install:
  - npm install
  - ./node_modules/.bin/jspm config registries.github.auth $GH_TOKEN
  - ./node_modules/.bin/jspm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./node_modules/.bin/gulp build
  - ./node_modules/.bin/gulp coveralls
